services:
  - type: web
    name: sweetlabbakery
    runtime: java
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: java -jar backend/target/sweetlabbakery.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
